python-interpreter-path = "venv/bin/python"
python_interpreter_path = "venv/bin/python"

search-path = ["backend"]
search_path = ["backend"]

project-includes = ["backend/**/*.py"]
project_includes = ["backend/**/*.py"]

project-excludes = ["**/venv/**", "**/.venv/**", "**/__pycache__/**"]
project_excludes = ["**/venv/**", "**/.venv/**", "**/__pycache__/**"]
